In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter('ignore')
import re
import string
import nltk

In [3]:
#Data Exploration and Preprocessing

data=pd.read_csv('D:\\blogs.csv')
data

Data              Labels
0     Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...         alt.atheism
1     Newsgroups: alt.atheism\nPath: cantaloupe.srv....         alt.atheism
2     Path: cantaloupe.srv.cs.cmu.edu!das-news.harva...         alt.atheism
3     Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...         alt.atheism
4     Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:53...         alt.atheism
...                                                 ...                 ...
1995  Xref: cantaloupe.srv.cs.cmu.edu talk.abortion:...  talk.religion.misc
1996  Xref: cantaloupe.srv.cs.cmu.edu talk.religion....  talk.religion.misc
1997  Xref: cantaloupe.srv.cs.cmu.edu talk.origins:4...  talk.religion.misc
1998  Xref: cantaloupe.srv.cs.cmu.edu talk.religion....  talk.religion.misc
1999  Xref: cantaloupe.srv.cs.cmu.edu sci.skeptic:43...  talk.religion.misc

[2000 rows x 2 columns]

In [5]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\SIDDHARTH\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\SIDDHARTH\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [7]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Data    2000 non-null   object
 1   Labels  2000 non-null   object
dtypes: object(2)
memory usage: 31.4+ KB


In [9]:
def clean(x):
    x=x.lower()
    x=re.sub('[\.*?/]','',x)
    x=re.sub('[%s]' %re.escape(string.punctuation),'',x)
    x=re.sub('w*\d\w*','',x)
    x=re.sub('[0-9]','',x)
    x=re.sub('[''""..,]','',x)
    return x
cleaned_data=lambda x:clean(x)

In [11]:
data['Data']=data.Data.apply(cleaned_data)
data

Data              Labels
0     path cantaloupesrvcscmuedumagnesiumclubcccmued...         alt.atheism
1     newsgroups altatheism\npath cantaloupesrvcscmu...         alt.atheism
2     path cantaloupesrvcscmuedudasnewsharvardedunoc...         alt.atheism
3     path cantaloupesrvcscmuedumagnesiumclubcccmued...         alt.atheism
4     xref cantaloupesrvcscmuedu altatheism talkreli...         alt.atheism
...                                                 ...                 ...
1995  xref cantaloupesrvcscmuedu talkabortion altath...  talk.religion.misc
1996  xref cantaloupesrvcscmuedu talkreligionmisc ta...  talk.religion.misc
1997  xref cantaloupesrvcscmuedu talkorigins talkrel...  talk.religion.misc
1998  xref cantaloupesrvcscmuedu talkreligionmisc al...  talk.religion.misc
1999  xref cantaloupesrvcscmuedu sciskeptic talkpoli...  talk.religion.misc

[2000 rows x 2 columns]

In [31]:
import nltk
from nltk.tokenize import word_tokenize

# 1️⃣ Download tokenizer if not done already
nltk.download('punkt')

# 2️⃣ Clean and convert all to string
data['Data'] = data['Data'].astype(str)

# 3️⃣ Tokenize safely
data['Data'] = data['Data'].apply(word_tokenize)

# ✅ Now each row is a list of tokens
print(data['Data'].head())


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\SIDDHARTH\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


0    [[, ', p, ', ,, ', h, ', ,, ', ', ,, ', c, ', ...
1    [[, 'n, ', ,, ', e, ', ,, ', w, ', ,, ', g, ',...
2    [[, ', p, ', ,, ', h, ', ,, ', ', ,, ', c, ', ...
3    [[, ', p, ', ,, ', h, ', ,, ', ', ,, ', c, ', ...
4    [[, ', x, ', ,, ', r, ', ,, ', e, ', ,, ', f, ...
Name: Data, dtype: object


In [33]:
stopword=set(stopwords.words('english'))
data['Data']=data['Data'].apply(lambda tokens:[word for word in tokens if word not in stopword])
data

Data              Labels
0     [[, ', p, ', ,, ', h, ', ,, ', ', ,, ', c, ', ...         alt.atheism
1     [[, 'n, ', ,, ', e, ', ,, ', w, ', ,, ', g, ',...         alt.atheism
2     [[, ', p, ', ,, ', h, ', ,, ', ', ,, ', c, ', ...         alt.atheism
3     [[, ', p, ', ,, ', h, ', ,, ', ', ,, ', c, ', ...         alt.atheism
4     [[, ', x, ', ,, ', r, ', ,, ', e, ', ,, ', f, ...         alt.atheism
...                                                 ...                 ...
1995  [[, ', x, ', ,, ', r, ', ,, ', e, ', ,, ', f, ...  talk.religion.misc
1996  [[, ', x, ', ,, ', r, ', ,, ', e, ', ,, ', f, ...  talk.religion.misc
1997  [[, ', x, ', ,, ', r, ', ,, ', e, ', ,, ', f, ...  talk.religion.misc
1998  [[, ', x, ', ,, ', r, ', ,, ', e, ', ,, ', f, ...  talk.religion.misc
1999  [[, ', x, ', ,, ', r, ', ,, ', e, ', ,, ', f, ...  talk.religion.misc

[2000 rows x 2 columns]

In [35]:
data['Data']=[" ".join(doc) for  doc in data['Data']]
tf=TfidfVectorizer()
tfmatrix=tf.fit_transform(data['Data'])

print('TF_TDF MATRIX:','\n',tfmatrix.toarray())
print('COLUMNS NAMES:','\n',tf.get_feature_names_out())

TF_TDF MATRIX: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
COLUMNS NAMES: 
 ['x08' 'x0c' 'x1a' 'x1b']


In [37]:
extracted_data=pd.DataFrame(tfmatrix.toarray(),columns=tf.get_feature_names_out())
extracted_data

x08  x0c  x1a  x1b
0     0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.0
...   ...  ...  ...  ...
1995  0.0  0.0  0.0  0.0
1996  0.0  0.0  0.0  0.0
1997  0.0  0.0  0.0  0.0
1998  0.0  0.0  0.0  0.0
1999  0.0  0.0  0.0  0.0

[2000 rows x 4 columns]

In [39]:
#Naive Bayes Model for Text Classification & Evaluation

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report
features=tf.fit_transform(data['Data'])
target=data['Labels']

In [49]:
x_train,x_test,y_train,y_test=train_test_split(features,target,test_size=0.2,random_state=43)

In [51]:
from sklearn.naive_bayes import MultinomialNB

In [53]:
model=MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB()

In [55]:
y_pred=model.predict(x_test)
print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 0.025


In [57]:
print("Classification Report",classification_report(y_test,y_pred))

Classification Report                           precision    recall  f1-score   support

             alt.atheism       0.00      0.00      0.00        16
           comp.graphics       0.00      0.00      0.00        19
 comp.os.ms-windows.misc       0.00      0.00      0.00        12
comp.sys.ibm.pc.hardware       0.00      0.00      0.00        20
   comp.sys.mac.hardware       0.00      0.00      0.00        16
          comp.windows.x       0.00      0.00      0.00        17
            misc.forsale       0.00      0.00      0.00        18
               rec.autos       0.00      0.00      0.00        17
         rec.motorcycles       0.00      0.00      0.00        23
      rec.sport.baseball       0.00      0.00      0.00        28
        rec.sport.hockey       0.03      1.00      0.05        10
               sci.crypt       0.00      0.00      0.00        19
         sci.electronics       0.00      0.00      0.00        29
                 sci.med       0.00      0.00      0.

In [61]:
#Sentiment Analysis

from textblob import TextBlob
def get_sentiment(text):
    analysis=TextBlob(text)
    if analysis.sentiment.polarity>0:
        return 'Positive'
    elif analysis.sentiment.polarity<0:
        return 'Negitive'
    else:
        return 'Neutral'
    
data['Sentiment']=data['Data'].apply(get_sentiment)
print(data[['Labels','Sentiment']])

                  Labels Sentiment
0            alt.atheism   Neutral
1            alt.atheism   Neutral
2            alt.atheism   Neutral
3            alt.atheism   Neutral
4            alt.atheism   Neutral
...                  ...       ...
1995  talk.religion.misc   Neutral
1996  talk.religion.misc   Neutral
1997  talk.religion.misc   Neutral
1998  talk.religion.misc   Neutral
1999  talk.religion.misc   Neutral

[2000 rows x 2 columns]


In [63]:
sentiment_distribution=data.groupby('Labels')['Sentiment'].value_counts()
print(sentiment_distribution)

Labels                    Sentiment
alt.atheism               Neutral      100
comp.graphics             Neutral      100
comp.os.ms-windows.misc   Neutral      100
comp.sys.ibm.pc.hardware  Neutral      100
comp.sys.mac.hardware     Neutral      100
comp.windows.x            Neutral      100
misc.forsale              Neutral      100
rec.autos                 Neutral      100
rec.motorcycles           Neutral      100
rec.sport.baseball        Neutral      100
rec.sport.hockey          Neutral      100
sci.crypt                 Neutral      100
sci.electronics           Neutral      100
sci.med                   Neutral      100
sci.space                 Neutral      100
soc.religion.christian    Neutral      100
talk.politics.guns        Neutral      100
talk.politics.mideast     Neutral      100
talk.politics.misc        Neutral      100
talk.religion.misc        Neutral      100
Name: count, dtype: int64
